In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/dsca/Downloads/cereal (1).csv")
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [3]:
# Question 1
pd.crosstab(df['mfr'],df['type'])

type   C  H
mfr
A      0  1
G     22  0
K     23  0
N      5  1
P      9  0
Q      7  1
R      8  0

In [4]:
# Question 2
column = False
for columns in df:
    if columns == 'calories':
        column = True
    if column:
        print('Five number summary for '+columns)
        print(df[columns].describe()[3:])
        print('\n')

Five number summary for calories
min     50.0
25%    100.0
50%    110.0
75%    110.0
max    160.0
Name: calories, dtype: float64


Five number summary for protein
min    1.0
25%    2.0
50%    3.0
75%    3.0
max    6.0
Name: protein, dtype: float64


Five number summary for fat
min    0.0
25%    0.0
50%    1.0
75%    2.0
max    5.0
Name: fat, dtype: float64


Five number summary for sodium
min      0.0
25%    130.0
50%    180.0
75%    210.0
max    320.0
Name: sodium, dtype: float64


Five number summary for fiber
min     0.0
25%     1.0
50%     2.0
75%     3.0
max    14.0
Name: fiber, dtype: float64


Five number summary for carbo
min    -1.0
25%    12.0
50%    14.0
75%    17.0
max    23.0
Name: carbo, dtype: float64


Five number summary for sugars
min    -1.0
25%     3.0
50%     7.0
75%    11.0
max    15.0
Name: sugars, dtype: float64


Five number summary for potass
min     -1.0
25%     40.0
50%     90.0
75%    120.0
max    330.0
Name: potass, dtype: float64


Five number summary for vitamins
min      0.0
25%     25.0
50%     25.0
75%     25.0
max    100.0
Name: vitamins, dtype: float64


Five number summary for shelf
min    1.0
25%    1.0
50%    2.0
75%    3.0
max    3.0
Name: shelf, dtype: float64


Five number summary for weight
min    0.5
25%    1.0
50%    1.0
75%    1.0
max    1.5
Name: weight, dtype: float64


Five number summary for cups
min    0.25
25%    0.67
50%    0.75
75%    1.00
max    1.50
Name: cups, dtype: float64


Five number summary for rating
min    18.042851
25%    33.174094
50%    40.400208
75%    50.828392
max    93.704912
Name: rating, dtype: float64

In [5]:
# Question 3
df= df.replace (-1,df.mean())
df

C:\Users\dsca\AppData\Local\Temp\ipykernel_15256\2666461281.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df= df.replace (-1,df.mean())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,96.077922,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.000000,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.000000,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.000000,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.000000,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.000000,25,1,1.0,0.75,36.187559

In [6]:
# Question 4
boo = False
for value in df:
    if value == 'calories':
        boo = True
    if boo:
        mean = df[value].mean()
        std = df[value].std()
        median = df[value].median()
        
        upper = mean + 2.0*std
        lower = mean - 2.0*std
        
        print(upper)
        print(lower)
        
        df[value][df[value]>upper] = median
        df[value][df[value]<lower] = median

145.85135499675857
67.9148787694752
4.735034042345613
0.35587504856347785
3.0259321319477985
-0.9999581059737725
327.339915155511
-7.989265804861674
6.918675980722499
-2.6147798768263955
22.56317587781328
7.03675665718419
15.724502549519089
-1.674578447646935
237.55790609570988
-40.359053000752894
72.93179824788585
-16.43829175437936
3.8728404080637837
0.5427440075206318
1.3305639890841738
0.7286567901366051
1.2864712379327892
0.3556066841451335
70.76028247448342
14.571127499542552

C:\Users\dsca\AppData\Local\Temp\ipykernel_15256\1356109070.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[value][df[value]>upper] = median
C:\Users\dsca\AppData\Local\Temp\ipykernel_15256\1356109070.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[value][df[value]<lower] = median

In [19]:
# Question 5
column = False
for columns in df:
    if columns == 'calories':
        column = True
    if columns == 'rating':
        column = False
    if column:
        print('Five number summary for '+columns)
        print(df[columns].describe()[3:])
        print('\n')

Five number summary for calories
min     70.0
25%    100.0
50%    110.0
75%    110.0
max    140.0
Name: calories, dtype: float64


Five number summary for protein
min    1.0
25%    2.0
50%    3.0
75%    3.0
max    4.0
Name: protein, dtype: float64


Five number summary for fat
min    0.0
25%    0.0
50%    1.0
75%    1.0
max    3.0
Name: fat, dtype: float64


Five number summary for sodium
min      0.0
25%    130.0
50%    180.0
75%    210.0
max    320.0
Name: sodium, dtype: float64


Five number summary for fiber
min    0.0
25%    1.0
50%    2.0
75%    3.0
max    6.0
Name: fiber, dtype: float64


Five number summary for carbo
min     8.000000
25%    12.000000
50%    14.597403
75%    17.000000
max    22.000000
Name: carbo, dtype: float64


Five number summary for sugars
min     0.0
25%     3.0
50%     7.0
75%    11.0
max    15.0
Name: sugars, dtype: float64


Five number summary for potass
min     15.0
25%     45.0
50%     90.0
75%    110.0
max    230.0
Name: potass, dtype: float64


Five number summary for vitamins
min     0.0
25%    25.0
50%    25.0
75%    25.0
max    25.0
Name: vitamins, dtype: float64


Five number summary for shelf
min    1.0
25%    1.0
50%    2.0
75%    3.0
max    3.0
Name: shelf, dtype: float64


Five number summary for weight
min    0.83
25%    1.00
50%    1.00
75%    1.00
max    1.33
Name: weight, dtype: float64


Five number summary for cups
min    0.50
25%    0.67
50%    0.75
75%    1.00
max    1.25
Name: cups, dtype: float64

In [8]:
# Question 7
print("Correlation between calories and rating:")
print(df['calories'].corr(df['rating']))
print("They are correlated")

Correlation between calories and rating:
-0.5924474367236661
They are correlated

In [9]:
# Question 8
labels, categories = pd.factorize(df["mfr"])
df["labels"] = labels
print('correlation:'+str(df["rating"].corr(df["labels"])))
print("They are not very related")

correlation:-0.314776599400143
They are not very related

In [10]:
# Question 9
print('Worst cereal:'+str(df['name'].loc[df['rating']==df['rating'].min()]))
print('Best cereal:'+str(df['name'].loc[df['rating']==df['rating'].max()]))

Worst cereal:10    Cap'n'Crunch
Name: name, dtype: object
Best cereal:0    100% Bran
Name: name, dtype: object

In [11]:
# Question 10
print('Worst cereal:'+str(df['name'].loc[df['calories']==df['calories'].max()]))
print('Best cereal:'+str(df['name'].loc[df['calories']==df['calories'].min()]))

Worst cereal:39       Just Right Fruit & Nut
49    Nutri-Grain Almond-Raisin
70            Total Raisin Bran
Name: name, dtype: object
Best cereal:0    100% Bran
2     All-Bran
Name: name, dtype: object

In [12]:
# Question 11
pd.DataFrame(df.sort_values(by=['rating'],ascending=False)['name'].head(5))

                      name
0                100% Bran
63          Shredded Wheat
20  Cream of Wheat (Quick)
55            Puffed Wheat
54             Puffed Rice

In [13]:
# Question 12
print('Highest Sodium:'+str(df['name'].loc[df['sodium']==df['sodium'].max()]))

Highest Sodium:53    Product 19
Name: name, dtype: object

In [14]:
# Question 13
print('Lowest carb: '+str(df['name'].loc[df['carbo']==df['carbo'].min()]))

Lowest carb: 1            100% Natural Bran
3    All-Bran with Extra Fiber
Name: name, dtype: object

In [15]:
# Question 14
print('correlation coefficient:'+str(df['shelf'].corr(df['sugars'])))
print("They are not very correlated")

correlation coefficient:0.06786814075516648
They are not very correlated

In [16]:
# Question 15
print('Manufacturer: '+str(df['name'].loc[df['sugars']==df['sugars'].max()]))

Manufacturer: 30    Golden Crisp
66          Smacks
Name: name, dtype: object

In [17]:
# Question 16
# Same as Question 3

In [18]:
# Question 17
boo = False
for value in df:
    if value == 'calories':
        boo = True
    if boo:
        mean = df[value].mean()
        q1 = df[value].quantile(0.25)
        q3 = df[value].quantile(0.75)
        iqr = q3-q1
        median = df[value].median()
        
        upper = q3 + 1.5*iqr
        lower = q1 - 1.5*iqr
        print('Number of outliers(IQR) in '+value+':')
        print(df[value].loc[np.logical_and(df[value]>upper,df[value]<lower)].count())

Number of outliers(IQR) in calories:
0
Number of outliers(IQR) in protein:
0
Number of outliers(IQR) in fat:
0
Number of outliers(IQR) in sodium:
0
Number of outliers(IQR) in fiber:
0
Number of outliers(IQR) in carbo:
0
Number of outliers(IQR) in sugars:
0
Number of outliers(IQR) in potass:
0
Number of outliers(IQR) in vitamins:
0
Number of outliers(IQR) in shelf:
0
Number of outliers(IQR) in weight:
0
Number of outliers(IQR) in cups:
0
Number of outliers(IQR) in rating:
0
Number of outliers(IQR) in labels:
0